data:
  class_path: data_modules.CombinedDataModule
  init_args:
    batch_size: 2
    num_workers: 4
    load_config:
      train:
        ACDC:
          load_pseudo_labels: True
          pseudo_label_dir: pseudo_labels_train_ACDC_cma_deeplabv2
          load_keys:
            - image
            - semantic
            - image_ref
          transforms:
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.RandomCrop
              init_args:
                size: 
                  - 1080
                  - 1080
                cat_max_ratio: 0.75
            - class_path: data_modules.transforms.RandomHorizontalFlip
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
      val:
        ACDC:
          load_keys:
            - image
            - semantic
          transforms:
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
      test:
        ACDC:
          load_keys:
            - image
            - semantic
          transforms:
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
        # ACG:
        #   conditions:
        #     - fog
        #     - night
        #     - rain
        #     - snow
        #   load_keys:
        #     - image
        #     - semantic
        #   transforms:
        #     - class_path: data_modules.transforms.ToTensor
        #     - class_path: data_modules.transforms.ConvertImageDtype
        #     - class_path: data_modules.transforms.Normalize
      predict:
        ACDC:
          predict_on: val
          load_keys:
            - image
          transforms:
            - class_path: data_modules.transforms.ToTensor
            - class_path: data_modules.transforms.ConvertImageDtype
            - class_path: data_modules.transforms.Normalize
model:
  class_path: models.CMAModel
  init_args:
    entropy_loss_weight: 1.0
    contrastive_loss_weight: 1.0
    freeze_decoder: True
    projection_head_lr_factor: 10.0
    ema_momentum: 0.9999
    backbone:
      class_path: models.backbones.ResNet
      init_args:
        model_type: resnet101_v1c
        strides:
          - 1
          - 2
          - 1
          - 1
        dilations:
          - 1
          - 1
          - 2
          - 4
        pretrained: cityscapes
    head:
      class_path: models.heads.DeepLabV2Head
      init_args:
        in_channels: 2048
        in_index: 3
        num_classes: 19
        pretrained: cityscapes
    contrastive_head:
      class_path: models.heads.ProjectionHead
      init_args:
        in_channels: 2048
        in_index: 3
        channels: 128
    alignment_backbone:
      class_path: models.backbones.VGG
      init_args:
        model_type: vgg16
        pretrained: imagenet
        out_indices:
          - 2
          - 3
          - 4
    alignment_head:
      class_path: models.heads.UAWarpCHead
      init_args:
        in_index:
          - 0
          - 1
        input_transform: multiple_select
        estimate_uncertainty: True
        pretrained: megadepth
    self_training_loss:
      class_path: torch.nn.CrossEntropyLoss
      init_args:
        ignore_index: 255
    entropy_loss:
      class_path: models.losses.NormalizedEntropyLoss
    contrastive_loss:
      class_path: models.losses.CDCLoss
      init_args:
        feat_dim: 128
        temperature: 0.3
        num_grid: 7
        queue_len: 65536
        warm_up_steps: 2500
        confidence_threshold: 0.2
    metrics:
      val:
        ACDC:
          - class_path: helpers.metrics.IoU
            init_args:
              num_classes: 19
              ignore_index: 255
              average: macro
      test:
        ACDC:
          - class_path: helpers.metrics.IoU
            init_args:
              num_classes: 19
              ignore_index: 255
              average: macro
        # ACG:
        #   - class_path: helpers.metrics.IoU
        #     init_args:
        #       num_classes: 19
        #       ignore_index: 255
        #       average: macro
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.00000002
    weight_decay: 0.01
lr_scheduler:
  class_path: helpers.lr_scheduler.LinearWarmupLinearLR
  init_args:
    warmup_iters: 1500
    warmup_ratio: 0.000001
    max_steps: 10000
trainer:
  max_steps: 10000
  val_check_interval: 1000
  check_val_every_n_epoch: null
  sync_batchnorm: True
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: logs/cma_deeplabv2_acdc
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_train_steps: 1000
